MAIN: common.c common.h OTHER0 OTHER1
	gcc main.c common.c -o main.o

OTHER0: common.c common.h Creator.c
	gcc Creator.c common.c -o Creator.o
OTHER1: common.c common.h Coster.c
	gcc Coster.c common.c -o Coster.o
